apiVersion: v1
kind: Pod
metadata:
    labels:
        run: nacos
    name: nacos
spec:
    containers:
        -   env:
                -   name: MODE
                    value: standalone
            image: nacos/nacos-server:v2.1.2
            name: nacos
            volumeMounts:
                -   mountPath: /home/nacos/data
                    name: data
            resources: { }
    volumes:
        -   name: data
            nfs:
                path: /home/hongcai/lhc_data/nacos/data
                server: 222.201.187.50
    dnsPolicy: ClusterFirst
    restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
    labels:
        run: nacos
    name: nacos
spec:
    ports:
        -   port: 8848
            name: port1
            protocol: TCP
            nodePort: 30848
            targetPort: 8848
        -   port: 9848
            name: port2
            protocol: TCP
            nodePort: 31848
            targetPort: 9848
    selector:
        run: nacos
    type: NodePort